### PR TITLE
added styling

### PR DESCRIPTION
**Pull request by NathanMoes**
image

### CODE REVIEW

**Comment by NathanMoes** [comment]
Added background image as per the styling of the other pages, added the items of team stuff into a card. The grid for the team members is not sytling properly as the code that relates to it from the IonGrid in the function that returns it causes the problem.

**Comment by bailee-crandley** [comment]
Can you please make the team name above the profile picture bigger? Like so big that it's as wide as the profile picture.

**Comment by bailee-crandley** [comment]
Can you please add some indication as to who the team captain is? My preferred implementation would be that team captain is in bold and has an asterisk by their name with a little blurb under the table that says something like "* Team Captain", but I'm open to other ideas!

**Comment by NathanMoes** [comment]
> Can you please add some indication as to who the team captain is? My preferred implementation would be that team captain is in bold and has an asterisk by their name with a little blurb under the table that says something like "* Team Captain", but I'm open to other ideas!

I would if I knew who was team captain. But, I don't know how to find who is for each team

**Review by bailee-crandley — APPROVED** [review]

**Pull request merged**
