### PR TITLE
323 update profile page for the leafs data

### PR DESCRIPTION
**Pull request by NathanMoes**
image

### CODE REVIEW

**Comment by NathanMoes** [comment]
Should work fine, error before is now unable to replicate. Error before involved reading into array beyoned index but now before each check it will make sure the index is within range, solving issue. Anyone reviewing please take a moment to run up the page to check make see for any other erros. BUT it SHOULD be perfectly fine, as it was on my end with testing. I am just kinda sus

**Comment by NathanMoes** [comment]
image

**Comment by NathanMoes** [comment]
image

**Comment by NathanMoes** [comment]
> image

Think it was mentioned to put calendar below the badges and stuff but next to it kinda looks good too IMO

**Comment by bailee-crandley** [comment]
Is there a reason that the calendar moved to the right side?

**Comment by NathanMoes** [comment]
> Is there a reason that the calendar moved to the right side?

I thought it might look nicer. But its a simple change

**Comment by juroc95** [comment]
Is it good to merge?

**Comment by bailee-crandley** [comment]
> > Is there a reason that the calendar moved to the right side?
> 
> I thought it might look nicer. But its a simple change

Do you remember how we talked about it going underneath the area that says badges? Is this something you want to do in this PR or in a future PR?

**Comment by bailee-crandley** [comment]
So in the end, we want the calendar where this green box is: 
image

**Comment by NathanMoes** [comment]
image
image

image
image

**Comment by NathanMoes** [comment]
> image
> 
> image
> 
> image
> 
> image

removed the color difference on last 2 images

**Review by bailee-crandley — APPROVED** [review]

**Pull request merged**
