### PR TITLE
Manual steps logging page styling

### PR DESCRIPTION
**Pull request by NathanMoes**
image
image
image
image

### CODE REVIEW

**Comment by NathanMoes** [comment]
note the tabs on the bottom are only beacuse its in browers thinking its android

**Comment by NathanMoes** [comment]
image

**Comment by xuvea** [comment]
Would it be possible to set a max width for it so that there isn't a large empty space on the right of the steps?

**Comment by NathanMoes** [comment]
> Would it be possible to set a max width for it so that there isn't a large empty space on the right of the steps?

image
This look better? Only other thing that I can do is decrease overall size for the card overall. But I Don't think it will look good if its much smaller on big screens

**Comment by xuvea** [comment]
The original looks better I think, it lined up better with the buttons and text.

**Comment by bailee-crandley** [comment]
I was just reading an article this morning on table ui design and one of the thing it said is that number should be right-aligned and monospace if you can so that user's can easily see the scope of the number. For example, 100000 has 6 digits while 1000000 has 7 digits. Also I think we want the column headers to be lined up with the data. https://medium.com/design-with-figma/the-ultimate-guide-to-designing-data-tables-7db29713a85a

**Comment by NathanMoes** [comment]
image

**Comment by xuvea** [comment]
Looks great!

**Review by xuvea — APPROVED** [review]
Styling is looking great.

**Pull request merged**
