### PR TITLE
141 fix eslint script

### PR DESCRIPTION
**Pull request by NathanMoes**
…e complicated fixes thus, eslint cannot fix them on its own. Please test on your own to validate.

### CODE REVIEW

**Comment by NathanMoes** [comment]
Errors I'm getting now from eslint are all ( except one in command line) valid complaints. Mostly in typescript complaining about implicit type any

**Review by xuvea — APPROVED** [review]
Looks all good.

**Comment by bailee-crandley** [comment]
image
Is this PR meant to fix this issue?

**Comment by NathanMoes** [comment]
> 
I cannot replicate this error when I run on my machine. I don't know exactly why. I'll investigate this and see if I can find a fix

**Comment by NathanMoes** [comment]
> > 
> 
> I cannot replicate this error when I run on my machine. I don't know exactly why. I'll investigate this and see if I can find a fix

I am still unable to resolve this issue specifily and unable to repeat it on my machine. My only guess is that somehow the import statement is not correct or somehow a control character was copy and pasted in somewhere. Though I honeslty do not know.

**Pull request merged**
