### PR TITLE
175 main styling

### PR DESCRIPTION
**Pull request by NathanMoes**
Added responsive styling plus added a background. Honestly not sure what else to add in styling wise now.

### CODE REVIEW

**Comment by juroc95** [comment]
It seems that the newly applied styling is causing problems with loading the homepage. On both iOS and Android, a blank screen appears instead of the homepage when loading the homepage, and on the web, after logging out from a different page and trying to load the homepage by logging in again, a blank screen appears instead of the homepage. I will attach a screenshot.
Screenshot_1675417168
Simulator Screen Shot - iPhone 14 - 2023-02-03 at 01 36 31

**Comment by NathanMoes** [comment]
> It seems that the newly applied styling is causing problems with loading the homepage. On both iOS and Android, a blank screen appears instead of the homepage when loading the homepage, and on the web, after logging out from a different page and trying to load the homepage by logging in again, a blank screen appears instead of the homepage. I will attach a screenshot. Screenshot_1675417168 Simulator Screen Shot - iPhone 14 - 2023-02-03 at 01 36 31

image
Works fine now for me

**Comment by NathanMoes** [comment]
Oh wait, it gives error beacuse of chart with the past 7 days of steps. Ill see

**Comment by NathanMoes** [comment]
> Oh wait, it gives error beacuse of chart with the past 7 days of steps. Ill see

Will need to look into this more but it still is functional with it removed. Need to investiate the past logs data and its retrevial, as it does not seem to be working sometimes, and is thus causing errors with the chart

**Review by juroc95 — APPROVED** [review]
It is loading now. Thanks!

**Pull request merged**
