### PR TITLE
fixed hieght for hompage things temporary, made very basic outline fo…

### PR DESCRIPTION
**Pull request by NathanMoes**
…r the team home page

### CODE REVIEW

**Comment by bailee-crandley** [comment]
Screenshot please

**Comment by NathanMoes** [comment]
> Screenshot please

image

**Comment by NathanMoes** [comment]
image

**Comment by NathanMoes** [comment]
image

**Review by bailee-crandley — CHANGES_REQUESTED** [review]
Member status is actually something we're doing away with because we have no idea how to implement that. That's my bad for not updating the brainstorming pages. Once you take that off, this one should be good to merge!

**Comment by NathanMoes** [comment]
> 

image

**Review by bailee-crandley — APPROVED** [review]

**Pull request merged**
