### PR TITLE
main page restyling complete. Though thoughts needed on small screen …

### PR DESCRIPTION
**Pull request by NathanMoes**
…sized. It gets complicated to make it look decent...

### CODE REVIEW

**Comment by NathanMoes** [comment]
Notes on small screen sizes. Not sure if the todays steps should be at the top for sure. As making it at the top when small screen sizes is something that I honeslty have no idea how to do. As the grid system im pretty sure does not allow for complete reordering of columns at different sizes. I said reordering, not chaincing of the size mind you. I have done that. What I mean is, I have no idea how to have the steps in center for full, side for mid, but ALSO at the top for small. As that would have to make that column be first in that ordering. If you know how to do that then please tell me

**Comment by bailee-crandley** [comment]
Screenshots please

**Comment by NathanMoes** [comment]
image

**Comment by NathanMoes** [comment]
image

**Comment by NathanMoes** [comment]
image

**Comment by NathanMoes** [comment]
> Screenshots please

rogger rogger

**Review by bailee-crandley — APPROVED** [review]

**Pull request merged**
