### PR TITLE
styling changes for admin

### PR DESCRIPTION
**Pull request by RClift**
changed admin to have walktober logo background.  changed tables to use variables from the variables.css file
Capture
Capture modal

Trying to get tables to display alternating colors but that may be easier for backend to split up the mapping.

### CODE REVIEW

**Comment by marobertson11** [comment]
When you say split up the mapping, which part are you referring to?

**Comment by bailee-crandley** [comment]
Can you possibly make the modals to either be black or white depending on if they're in dark or light mode? I think Kevin did it with the post survey so you could ask him if you have questions.

**Comment by bailee-crandley** [comment]
Also, can any columns with numbers please be right aligned so that its easy to understand the magnitude? For example, 10 is smaller than 100 is smaller than 1000. It's also better if the number can be in a monospace font but don't stress too hard over that. This will probably be user steps, team total steps, and team average total steps.

**Comment by RClift** [comment]
updated images
Capture
modal

**Comment by bailee-crandley** [comment]
image
image

**Review by bailee-crandley — APPROVED** [review]

**Pull request merged**
