### PR TITLE
157 create calendar for profileuser leafs

### PR DESCRIPTION
**Pull request by NathanMoes**
Super basic outline for a small calendar. Will be able to add items in such as little leafs for the status of the person. But does need styling in order to make it both look better, and to function at lower screen sizes in reasonable ways. Though that I will leave for later on to implement once we have the icons/leafs to add in, that way the sizing can be done corectly for the items.

### CODE REVIEW

**Comment by bailee-crandley** [comment]
Can you please add a screenshot of the calendar you made?

**Comment by NathanMoes** [comment]
> Can you please add a screenshot of the calendar you made?

image

**Comment by bailee-crandley** [comment]
It looks good! Do you have logic implemented yet so that the calendar will start on the right day of the week? For example, in 2022, Oct 1 was on the 6th day of the week (Saturday), in 2023, its on the 7th day of the week (Sunday), in 2024, its on the second day of the week (Tuesday).

**Review by bailee-crandley — APPROVED** [review]

**Comment by NathanMoes** [comment]
Indeed I did! That's the part that probably took the longest to figure out,
but it works. Basically it will just display the current year's October.
Done by getting the date in run time when the page is loaded. It then
checks the year, and constructs a date object with that years first day of
october. Then conditionally looks to see which day of the week is the
first. Next it will increment the days each day as it goes along.

**Pull request merged**
